// GENERATED FILE - do not edit by hand.
// Regenerate with: python3 tools/gen_codes.py
// Source: ISO 4217 via pycountry; minor units via CLDR/babel
// Generated: 2026-09-04T21:18:03Z

const std = @import("std");

/// One ISO 4217 currency entry. `minor_units` is the number of decimal digits
/// the currency is normally written with; amounts are stored as integers in
/// those minor units so that money never travels as a float.
pub const Currency = struct {
    code: [3]u8,
    numeric: u16,
    minor_units: u8,
    name: []const u8,
};

/// Sorted by alphabetic code so lookups can use binary search.
pub const table = [_]Currency{
    .{ .code = "AED".*, .numeric = 784, .minor_units = 2, .name = "UAE Dirham" },
    .{ .code = "AFN".*, .numeric = 971, .minor_units = 0, .name = "Afghani" },
    .{ .code = "ALL".*, .numeric = 8, .minor_units = 0, .name = "Lek" },
    .{ .code = "AMD".*, .numeric = 51, .minor_units = 2, .name = "Armenian Dram" },
    .{ .code = "AOA".*, .numeric = 973, .minor_units = 2, .name = "Kwanza" },
    .{ .code = "ARS".*, .numeric = 32, .minor_units = 2, .name = "Argentine Peso" },
    .{ .code = "AUD".*, .numeric = 36, .minor_units = 2, .name = "Australian Dollar" },
    .{ .code = "AWG".*, .numeric = 533, .minor_units = 2, .name = "Aruban Florin" },
    .{ .code = "AZN".*, .numeric = 944, .minor_units = 2, .name = "Azerbaijan Manat" },
    .{ .code = "BAM".*, .numeric = 977, .minor_units = 2, .name = "Convertible Mark" },
    .{ .code = "BBD".*, .numeric = 52, .minor_units = 2, .name = "Barbados Dollar" },
    .{ .code = "BDT".*, .numeric = 50, .minor_units = 2, .name = "Taka" },
    .{ .code = "BHD".*, .numeric = 48, .minor_units = 3, .name = "Bahraini Dinar" },
    .{ .code = "BIF".*, .numeric = 108, .minor_units = 0, .name = "Burundi Franc" },
    .{ .code = "BMD".*, .numeric = 60, .minor_units = 2, .name = "Bermudian Dollar" },
    .{ .code = "BND".*, .numeric = 96, .minor_units = 2, .name = "Brunei Dollar" },
    .{ .code = "BOB".*, .numeric = 68, .minor_units = 2, .name = "Boliviano" },
    .{ .code = "BOV".*, .numeric = 984, .minor_units = 2, .name = "Mvdol" },
    .{ .code = "BRL".*, .numeric = 986, .minor_units = 2, .name = "Brazilian Real" },
    .{ .code = "BSD".*, .numeric = 44, .minor_units = 2, .name = "Bahamian Dollar" },
    .{ .code = "BTN".*, .numeric = 64, .minor_units = 2, .name = "Ngultrum" },
    .{ .code = "BWP".*, .numeric = 72, .minor_units = 2, .name = "Pula" },
    .{ .code = "BYN".*, .numeric = 933, .minor_units = 2, .name = "Belarusian Ruble" },
    .{ .code = "BZD".*, .numeric = 84, .minor_units = 2, .name = "Belize Dollar" },
    .{ .code = "CAD".*, .numeric = 124, .minor_units = 2, .name = "Canadian Dollar" },
    .{ .code = "CDF".*, .numeric = 976, .minor_units = 2, .name = "Congolese Franc" },
    .{ .code = "CHE".*, .numeric = 947, .minor_units = 2, .name = "WIR Euro" },
    .{ .code = "CHF".*, .numeric = 756, .minor_units = 2, .name = "Swiss Franc" },
    .{ .code = "CHW".*, .numeric = 948, .minor_units = 2, .name = "WIR Franc" },
    .{ .code = "CLF".*, .numeric = 990, .minor_units = 4, .name = "Unidad de Fomento" },
    .{ .code = "CLP".*, .numeric = 152, .minor_units = 0, .name = "Chilean Peso" },
    .{ .code = "CNY".*, .numeric = 156, .minor_units = 2, .name = "Yuan Renminbi" },
    .{ .code = "COP".*, .numeric = 170, .minor_units = 2, .name = "Colombian Peso" },
    .{ .code = "COU".*, .numeric = 970, .minor_units = 2, .name = "Unidad de Valor Real" },
    .{ .code = "CRC".*, .numeric = 188, .minor_units = 2, .name = "Costa Rican Colon" },
    .{ .code = "CUP".*, .numeric = 192, .minor_units = 2, .name = "Cuban Peso" },
    .{ .code = "CVE".*, .numeric = 132, .minor_units = 2, .name = "Cabo Verde Escudo" },
    .{ .code = "CZK".*, .numeric = 203, .minor_units = 2, .name = "Czech Koruna" },
    .{ .code = "DJF".*, .numeric = 262, .minor_units = 0, .name = "Djibouti Franc" },
    .{ .code = "DKK".*, .numeric = 208, .minor_units = 2, .name = "Danish Krone" },
    .{ .code = "DOP".*, .numeric = 214, .minor_units = 2, .name = "Dominican Peso" },
    .{ .code = "DZD".*, .numeric = 12, .minor_units = 2, .name = "Algerian Dinar" },
    .{ .code = "EGP".*, .numeric = 818, .minor_units = 2, .name = "Egyptian Pound" },
    .{ .code = "ERN".*, .numeric = 232, .minor_units = 2, .name = "Nakfa" },
    .{ .code = "ETB".*, .numeric = 230, .minor_units = 2, .name = "Ethiopian Birr" },
    .{ .code = "EUR".*, .numeric = 978, .minor_units = 2, .name = "Euro" },
    .{ .code = "FJD".*, .numeric = 242, .minor_units = 2, .name = "Fiji Dollar" },
    .{ .code = "FKP".*, .numeric = 238, .minor_units = 2, .name = "Falkland Islands Pound" },
    .{ .code = "GBP".*, .numeric = 826, .minor_units = 2, .name = "Pound Sterling" },
    .{ .code = "GEL".*, .numeric = 981, .minor_units = 2, .name = "Lari" },
    .{ .code = "GHS".*, .numeric = 936, .minor_units = 2, .name = "Ghana Cedi" },
    .{ .code = "GIP".*, .numeric = 292, .minor_units = 2, .name = "Gibraltar Pound" },
    .{ .code = "GMD".*, .numeric = 270, .minor_units = 2, .name = "Dalasi" },
    .{ .code = "GNF".*, .numeric = 324, .minor_units = 0, .name = "Guinean Franc" },
    .{ .code = "GTQ".*, .numeric = 320, .minor_units = 2, .name = "Quetzal" },
    .{ .code = "GYD".*, .numeric = 328, .minor_units = 2, .name = "Guyana Dollar" },
    .{ .code = "HKD".*, .numeric = 344, .minor_units = 2, .name = "Hong Kong Dollar" },
    .{ .code = "HNL".*, .numeric = 340, .minor_units = 2, .name = "Lempira" },
    .{ .code = "HTG".*, .numeric = 332, .minor_units = 2, .name = "Gourde" },
    .{ .code = "HUF".*, .numeric = 348, .minor_units = 2, .name = "Forint" },
    .{ .code = "IDR".*, .numeric = 360, .minor_units = 2, .name = "Rupiah" },
    .{ .code = "ILS".*, .numeric = 376, .minor_units = 2, .name = "New Israeli Sheqel" },
    .{ .code = "INR".*, .numeric = 356, .minor_units = 2, .name = "Indian Rupee" },
    .{ .code = "IQD".*, .numeric = 368, .minor_units = 0, .name = "Iraqi Dinar" },
    .{ .code = "IRR".*, .numeric = 364, .minor_units = 0, .name = "Iranian Rial" },
    .{ .code = "ISK".*, .numeric = 352, .minor_units = 0, .name = "Iceland Krona" },
    .{ .code = "JMD".*, .numeric = 388, .minor_units = 2, .name = "Jamaican Dollar" },
    .{ .code = "JOD".*, .numeric = 400, .minor_units = 3, .name = "Jordanian Dinar" },
    .{ .code = "JPY".*, .numeric = 392, .minor_units = 0, .name = "Yen" },
    .{ .code = "KES".*, .numeric = 404, .minor_units = 2, .name = "Kenyan Shilling" },
    .{ .code = "KGS".*, .numeric = 417, .minor_units = 2, .name = "Som" },
    .{ .code = "KHR".*, .numeric = 116, .minor_units = 2, .name = "Riel" },
    .{ .code = "KMF".*, .numeric = 174, .minor_units = 0, .name = "Comorian Franc" },
    .{ .code = "KPW".*, .numeric = 408, .minor_units = 0, .name = "North Korean Won" },
    .{ .code = "KRW".*, .numeric = 410, .minor_units = 0, .name = "Won" },
    .{ .code = "KWD".*, .numeric = 414, .minor_units = 3, .name = "Kuwaiti Dinar" },
    .{ .code = "KYD".*, .numeric = 136, .minor_units = 2, .name = "Cayman Islands Dollar" },
    .{ .code = "KZT".*, .numeric = 398, .minor_units = 2, .name = "Tenge" },
    .{ .code = "LAK".*, .numeric = 418, .minor_units = 0, .name = "Lao Kip" },
    .{ .code = "LBP".*, .numeric = 422, .minor_units = 0, .name = "Lebanese Pound" },
    .{ .code = "LKR".*, .numeric = 144, .minor_units = 2, .name = "Sri Lanka Rupee" },
    .{ .code = "LRD".*, .numeric = 430, .minor_units = 2, .name = "Liberian Dollar" },
    .{ .code = "LSL".*, .numeric = 426, .minor_units = 2, .name = "Loti" },
    .{ .code = "LYD".*, .numeric = 434, .minor_units = 3, .name = "Libyan Dinar" },
    .{ .code = "MAD".*, .numeric = 504, .minor_units = 2, .name = "Moroccan Dirham" },
    .{ .code = "MDL".*, .numeric = 498, .minor_units = 2, .name = "Moldovan Leu" },
    .{ .code = "MGA".*, .numeric = 969, .minor_units = 0, .name = "Malagasy Ariary" },
    .{ .code = "MKD".*, .numeric = 807, .minor_units = 2, .name = "Denar" },
    .{ .code = "MMK".*, .numeric = 104, .minor_units = 0, .name = "Kyat" },
    .{ .code = "MNT".*, .numeric = 496, .minor_units = 2, .name = "Tugrik" },
    .{ .code = "MOP".*, .numeric = 446, .minor_units = 2, .name = "Pataca" },
    .{ .code = "MRU".*, .numeric = 929, .minor_units = 2, .name = "Ouguiya" },
    .{ .code = "MUR".*, .numeric = 480, .minor_units = 2, .name = "Mauritius Rupee" },
    .{ .code = "MVR".*, .numeric = 462, .minor_units = 2, .name = "Rufiyaa" },
    .{ .code = "MWK".*, .numeric = 454, .minor_units = 2, .name = "Malawi Kwacha" },
    .{ .code = "MXN".*, .numeric = 484, .minor_units = 2, .name = "Mexican Peso" },
    .{ .code = "MXV".*, .numeric = 979, .minor_units = 2, .name = "Mexican Unidad de Inversion (UDI)" },
    .{ .code = "MYR".*, .numeric = 458, .minor_units = 2, .name = "Malaysian Ringgit" },
    .{ .code = "MZN".*, .numeric = 943, .minor_units = 2, .name = "Mozambique Metical" },
    .{ .code = "NAD".*, .numeric = 516, .minor_units = 2, .name = "Namibia Dollar" },
    .{ .code = "NGN".*, .numeric = 566, .minor_units = 2, .name = "Naira" },
    .{ .code = "NIO".*, .numeric = 558, .minor_units = 2, .name = "Cordoba Oro" },
    .{ .code = "NOK".*, .numeric = 578, .minor_units = 2, .name = "Norwegian Krone" },
    .{ .code = "NPR".*, .numeric = 524, .minor_units = 2, .name = "Nepalese Rupee" },
    .{ .code = "NZD".*, .numeric = 554, .minor_units = 2, .name = "New Zealand Dollar" },
    .{ .code = "OMR".*, .numeric = 512, .minor_units = 3, .name = "Rial Omani" },
    .{ .code = "PAB".*, .numeric = 590, .minor_units = 2, .name = "Balboa" },
    .{ .code = "PEN".*, .numeric = 604, .minor_units = 2, .name = "Sol" },
    .{ .code = "PGK".*, .numeric = 598, .minor_units = 2, .name = "Kina" },
    .{ .code = "PHP".*, .numeric = 608, .minor_units = 2, .name = "Philippine Peso" },
    .{ .code = "PKR".*, .numeric = 586, .minor_units = 2, .name = "Pakistan Rupee" },
    .{ .code = "PLN".*, .numeric = 985, .minor_units = 2, .name = "Zloty" },
    .{ .code = "PYG".*, .numeric = 600, .minor_units = 0, .name = "Guarani" },
    .{ .code = "QAR".*, .numeric = 634, .minor_units = 2, .name = "Qatari Rial" },
    .{ .code = "RON".*, .numeric = 946, .minor_units = 2, .name = "Romanian Leu" },
    .{ .code = "RSD".*, .numeric = 941, .minor_units = 0, .name = "Serbian Dinar" },
    .{ .code = "RUB".*, .numeric = 643, .minor_units = 2, .name = "Russian Ruble" },
    .{ .code = "RWF".*, .numeric = 646, .minor_units = 0, .name = "Rwanda Franc" },
    .{ .code = "SAR".*, .numeric = 682, .minor_units = 2, .name = "Saudi Riyal" },
    .{ .code = "SBD".*, .numeric = 90, .minor_units = 2, .name = "Solomon Islands Dollar" },
    .{ .code = "SCR".*, .numeric = 690, .minor_units = 2, .name = "Seychelles Rupee" },
    .{ .code = "SDG".*, .numeric = 938, .minor_units = 2, .name = "Sudanese Pound" },
    .{ .code = "SEK".*, .numeric = 752, .minor_units = 2, .name = "Swedish Krona" },
    .{ .code = "SGD".*, .numeric = 702, .minor_units = 2, .name = "Singapore Dollar" },
    .{ .code = "SHP".*, .numeric = 654, .minor_units = 2, .name = "Saint Helena Pound" },
    .{ .code = "SLE".*, .numeric = 925, .minor_units = 2, .name = "Leone" },
    .{ .code = "SOS".*, .numeric = 706, .minor_units = 0, .name = "Somali Shilling" },
    .{ .code = "SRD".*, .numeric = 968, .minor_units = 2, .name = "Surinam Dollar" },
    .{ .code = "SSP".*, .numeric = 728, .minor_units = 2, .name = "South Sudanese Pound" },
    .{ .code = "STN".*, .numeric = 930, .minor_units = 2, .name = "Dobra" },
    .{ .code = "SVC".*, .numeric = 222, .minor_units = 2, .name = "El Salvador Colon" },
    .{ .code = "SYP".*, .numeric = 760, .minor_units = 0, .name = "Syrian Pound" },
    .{ .code = "SZL".*, .numeric = 748, .minor_units = 2, .name = "Lilangeni" },
    .{ .code = "THB".*, .numeric = 764, .minor_units = 2, .name = "Baht" },
    .{ .code = "TJS".*, .numeric = 972, .minor_units = 2, .name = "Somoni" },
    .{ .code = "TMT".*, .numeric = 934, .minor_units = 2, .name = "Turkmenistan New Manat" },
    .{ .code = "TND".*, .numeric = 788, .minor_units = 3, .name = "Tunisian Dinar" },
    .{ .code = "TOP".*, .numeric = 776, .minor_units = 2, .name = "Pa’anga" },
    .{ .code = "TRY".*, .numeric = 949, .minor_units = 2, .name = "Turkish Lira" },
    .{ .code = "TTD".*, .numeric = 780, .minor_units = 2, .name = "Trinidad and Tobago Dollar" },
    .{ .code = "TWD".*, .numeric = 901, .minor_units = 2, .name = "New Taiwan Dollar" },
    .{ .code = "TZS".*, .numeric = 834, .minor_units = 2, .name = "Tanzanian Shilling" },
    .{ .code = "UAH".*, .numeric = 980, .minor_units = 2, .name = "Hryvnia" },
    .{ .code = "UGX".*, .numeric = 800, .minor_units = 0, .name = "Uganda Shilling" },
    .{ .code = "USD".*, .numeric = 840, .minor_units = 2, .name = "US Dollar" },
    .{ .code = "USN".*, .numeric = 997, .minor_units = 2, .name = "US Dollar (Next day)" },
    .{ .code = "UYI".*, .numeric = 940, .minor_units = 0, .name = "Uruguay Peso en Unidades Indexadas (UI)" },
    .{ .code = "UYU".*, .numeric = 858, .minor_units = 2, .name = "Peso Uruguayo" },
    .{ .code = "UYW".*, .numeric = 927, .minor_units = 4, .name = "Unidad Previsional" },
    .{ .code = "UZS".*, .numeric = 860, .minor_units = 2, .name = "Uzbekistan Sum" },
    .{ .code = "VED".*, .numeric = 926, .minor_units = 2, .name = "Bolívar Soberano" },
    .{ .code = "VES".*, .numeric = 928, .minor_units = 2, .name = "Bolívar Soberano" },
    .{ .code = "VND".*, .numeric = 704, .minor_units = 0, .name = "Dong" },
    .{ .code = "VUV".*, .numeric = 548, .minor_units = 0, .name = "Vatu" },
    .{ .code = "WST".*, .numeric = 882, .minor_units = 2, .name = "Tala" },
    .{ .code = "XAD".*, .numeric = 396, .minor_units = 2, .name = "Arab Accounting Dinar" },
    .{ .code = "XAF".*, .numeric = 950, .minor_units = 0, .name = "CFA Franc BEAC" },
    .{ .code = "XAG".*, .numeric = 961, .minor_units = 2, .name = "Silver" },
    .{ .code = "XAU".*, .numeric = 959, .minor_units = 2, .name = "Gold" },
    .{ .code = "XBA".*, .numeric = 955, .minor_units = 2, .name = "Bond Markets Unit European Composite Unit (EURCO)" },
    .{ .code = "XBB".*, .numeric = 956, .minor_units = 2, .name = "Bond Markets Unit European Monetary Unit (E.M.U.-6)" },
    .{ .code = "XBC".*, .numeric = 957, .minor_units = 2, .name = "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)" },
    .{ .code = "XBD".*, .numeric = 958, .minor_units = 2, .name = "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)" },
    .{ .code = "XCD".*, .numeric = 951, .minor_units = 2, .name = "East Caribbean Dollar" },
    .{ .code = "XCG".*, .numeric = 532, .minor_units = 2, .name = "Caribbean Guilder" },
    .{ .code = "XDR".*, .numeric = 960, .minor_units = 2, .name = "SDR (Special Drawing Right)" },
    .{ .code = "XOF".*, .numeric = 952, .minor_units = 0, .name = "CFA Franc BCEAO" },
    .{ .code = "XPD".*, .numeric = 964, .minor_units = 2, .name = "Palladium" },
    .{ .code = "XPF".*, .numeric = 953, .minor_units = 0, .name = "CFP Franc" },
    .{ .code = "XPT".*, .numeric = 962, .minor_units = 2, .name = "Platinum" },
    .{ .code = "XSU".*, .numeric = 994, .minor_units = 2, .name = "Sucre" },
    .{ .code = "XTS".*, .numeric = 963, .minor_units = 2, .name = "Codes specifically reserved for testing purposes" },
    .{ .code = "XUA".*, .numeric = 965, .minor_units = 2, .name = "ADB Unit of Account" },
    .{ .code = "XXX".*, .numeric = 999, .minor_units = 2, .name = "The codes assigned for transactions where no currency is involved" },
    .{ .code = "YER".*, .numeric = 886, .minor_units = 0, .name = "Yemeni Rial" },
    .{ .code = "ZAR".*, .numeric = 710, .minor_units = 2, .name = "Rand" },
    .{ .code = "ZMW".*, .numeric = 967, .minor_units = 2, .name = "Zambian Kwacha" },
    .{ .code = "ZWG".*, .numeric = 924, .minor_units = 2, .name = "Zimbabwe Gold" },
};
