// GENERATED FILE - do not edit by hand.
// Regenerate with: python3 tools/gen_codes.py
// Source: ISO 639-1 and ISO 15924 via pycountry
// Generated: 2026-09-04T21:18:03Z

const std = @import("std");

pub const Language = struct {
    code: [2]u8,
    name: []const u8,
};

pub const Script = struct {
    code: [4]u8,
    name: []const u8,
};

/// ISO 639-1 two-letter language codes, sorted.
pub const languages = [_]Language{
    .{ .code = "aa".*, .name = "Afar" },
    .{ .code = "ab".*, .name = "Abkhazian" },
    .{ .code = "ae".*, .name = "Avestan" },
    .{ .code = "af".*, .name = "Afrikaans" },
    .{ .code = "ak".*, .name = "Akan" },
    .{ .code = "am".*, .name = "Amharic" },
    .{ .code = "an".*, .name = "Aragonese" },
    .{ .code = "ar".*, .name = "Arabic" },
    .{ .code = "as".*, .name = "Assamese" },
    .{ .code = "av".*, .name = "Avaric" },
    .{ .code = "ay".*, .name = "Aymara" },
    .{ .code = "az".*, .name = "Azerbaijani" },
    .{ .code = "ba".*, .name = "Bashkir" },
    .{ .code = "be".*, .name = "Belarusian" },
    .{ .code = "bg".*, .name = "Bulgarian" },
    .{ .code = "bi".*, .name = "Bislama" },
    .{ .code = "bm".*, .name = "Bambara" },
    .{ .code = "bn".*, .name = "Bengali" },
    .{ .code = "bo".*, .name = "Tibetan" },
    .{ .code = "br".*, .name = "Breton" },
    .{ .code = "bs".*, .name = "Bosnian" },
    .{ .code = "ca".*, .name = "Catalan" },
    .{ .code = "ce".*, .name = "Chechen" },
    .{ .code = "ch".*, .name = "Chamorro" },
    .{ .code = "co".*, .name = "Corsican" },
    .{ .code = "cr".*, .name = "Cree" },
    .{ .code = "cs".*, .name = "Czech" },
    .{ .code = "cu".*, .name = "Church Slavic" },
    .{ .code = "cv".*, .name = "Chuvash" },
    .{ .code = "cy".*, .name = "Welsh" },
    .{ .code = "da".*, .name = "Danish" },
    .{ .code = "de".*, .name = "German" },
    .{ .code = "dv".*, .name = "Divehi" },
    .{ .code = "dz".*, .name = "Dzongkha" },
    .{ .code = "ee".*, .name = "Ewe" },
    .{ .code = "el".*, .name = "Modern Greek (1453-)" },
    .{ .code = "en".*, .name = "English" },
    .{ .code = "eo".*, .name = "Esperanto" },
    .{ .code = "es".*, .name = "Spanish" },
    .{ .code = "et".*, .name = "Estonian" },
    .{ .code = "eu".*, .name = "Basque" },
    .{ .code = "fa".*, .name = "Persian" },
    .{ .code = "ff".*, .name = "Fulah" },
    .{ .code = "fi".*, .name = "Finnish" },
    .{ .code = "fj".*, .name = "Fijian" },
    .{ .code = "fo".*, .name = "Faroese" },
    .{ .code = "fr".*, .name = "French" },
    .{ .code = "fy".*, .name = "Western Frisian" },
    .{ .code = "ga".*, .name = "Irish" },
    .{ .code = "gd".*, .name = "Scottish Gaelic" },
    .{ .code = "gl".*, .name = "Galician" },
    .{ .code = "gn".*, .name = "Guarani" },
    .{ .code = "gu".*, .name = "Gujarati" },
    .{ .code = "gv".*, .name = "Manx" },
    .{ .code = "ha".*, .name = "Hausa" },
    .{ .code = "he".*, .name = "Hebrew" },
    .{ .code = "hi".*, .name = "Hindi" },
    .{ .code = "ho".*, .name = "Hiri Motu" },
    .{ .code = "hr".*, .name = "Croatian" },
    .{ .code = "ht".*, .name = "Haitian" },
    .{ .code = "hu".*, .name = "Hungarian" },
    .{ .code = "hy".*, .name = "Armenian" },
    .{ .code = "hz".*, .name = "Herero" },
    .{ .code = "ia".*, .name = "Interlingua (International Auxiliary Language Association)" },
    .{ .code = "id".*, .name = "Indonesian" },
    .{ .code = "ie".*, .name = "Interlingue" },
    .{ .code = "ig".*, .name = "Igbo" },
    .{ .code = "ii".*, .name = "Sichuan Yi" },
    .{ .code = "ik".*, .name = "Inupiaq" },
    .{ .code = "io".*, .name = "Ido" },
    .{ .code = "is".*, .name = "Icelandic" },
    .{ .code = "it".*, .name = "Italian" },
    .{ .code = "iu".*, .name = "Inuktitut" },
    .{ .code = "ja".*, .name = "Japanese" },
    .{ .code = "jv".*, .name = "Javanese" },
    .{ .code = "ka".*, .name = "Georgian" },
    .{ .code = "kg".*, .name = "Kongo" },
    .{ .code = "ki".*, .name = "Kikuyu" },
    .{ .code = "kj".*, .name = "Kuanyama" },
    .{ .code = "kk".*, .name = "Kazakh" },
    .{ .code = "kl".*, .name = "Kalaallisut" },
    .{ .code = "km".*, .name = "Khmer" },
    .{ .code = "kn".*, .name = "Kannada" },
    .{ .code = "ko".*, .name = "Korean" },
    .{ .code = "kr".*, .name = "Kanuri" },
    .{ .code = "ks".*, .name = "Kashmiri" },
    .{ .code = "ku".*, .name = "Kurdish" },
    .{ .code = "kv".*, .name = "Komi" },
    .{ .code = "kw".*, .name = "Cornish" },
    .{ .code = "ky".*, .name = "Kirghiz" },
    .{ .code = "la".*, .name = "Latin" },
    .{ .code = "lb".*, .name = "Luxembourgish" },
    .{ .code = "lg".*, .name = "Ganda" },
    .{ .code = "li".*, .name = "Limburgan" },
    .{ .code = "ln".*, .name = "Lingala" },
    .{ .code = "lo".*, .name = "Lao" },
    .{ .code = "lt".*, .name = "Lithuanian" },
    .{ .code = "lu".*, .name = "Luba-Katanga" },
    .{ .code = "lv".*, .name = "Latvian" },
    .{ .code = "mg".*, .name = "Malagasy" },
    .{ .code = "mh".*, .name = "Marshallese" },
    .{ .code = "mi".*, .name = "Maori" },
    .{ .code = "mk".*, .name = "Macedonian" },
    .{ .code = "ml".*, .name = "Malayalam" },
    .{ .code = "mn".*, .name = "Mongolian" },
    .{ .code = "mr".*, .name = "Marathi" },
    .{ .code = "ms".*, .name = "Malay (macrolanguage)" },
    .{ .code = "mt".*, .name = "Maltese" },
    .{ .code = "my".*, .name = "Burmese" },
    .{ .code = "na".*, .name = "Nauru" },
    .{ .code = "nb".*, .name = "Norwegian Bokmål" },
    .{ .code = "nd".*, .name = "North Ndebele" },
    .{ .code = "ne".*, .name = "Nepali (macrolanguage)" },
    .{ .code = "ng".*, .name = "Ndonga" },
    .{ .code = "nl".*, .name = "Dutch" },
    .{ .code = "nn".*, .name = "Norwegian Nynorsk" },
    .{ .code = "no".*, .name = "Norwegian" },
    .{ .code = "nr".*, .name = "South Ndebele" },
    .{ .code = "nv".*, .name = "Navajo" },
    .{ .code = "ny".*, .name = "Chichewa" },
    .{ .code = "oc".*, .name = "Occitan (post 1500)" },
    .{ .code = "oj".*, .name = "Ojibwa" },
    .{ .code = "om".*, .name = "Oromo" },
    .{ .code = "or".*, .name = "Oriya (macrolanguage)" },
    .{ .code = "os".*, .name = "Ossetian" },
    .{ .code = "pa".*, .name = "Panjabi" },
    .{ .code = "pi".*, .name = "Pali" },
    .{ .code = "pl".*, .name = "Polish" },
    .{ .code = "ps".*, .name = "Pushto" },
    .{ .code = "pt".*, .name = "Portuguese" },
    .{ .code = "qu".*, .name = "Quechua" },
    .{ .code = "rm".*, .name = "Romansh" },
    .{ .code = "rn".*, .name = "Rundi" },
    .{ .code = "ro".*, .name = "Romanian" },
    .{ .code = "ru".*, .name = "Russian" },
    .{ .code = "rw".*, .name = "Kinyarwanda" },
    .{ .code = "sa".*, .name = "Sanskrit" },
    .{ .code = "sc".*, .name = "Sardinian" },
    .{ .code = "sd".*, .name = "Sindhi" },
    .{ .code = "se".*, .name = "Northern Sami" },
    .{ .code = "sg".*, .name = "Sango" },
    .{ .code = "sh".*, .name = "Serbo-Croatian" },
    .{ .code = "si".*, .name = "Sinhala" },
    .{ .code = "sk".*, .name = "Slovak" },
    .{ .code = "sl".*, .name = "Slovenian" },
    .{ .code = "sm".*, .name = "Samoan" },
    .{ .code = "sn".*, .name = "Shona" },
    .{ .code = "so".*, .name = "Somali" },
    .{ .code = "sq".*, .name = "Albanian" },
    .{ .code = "sr".*, .name = "Serbian" },
    .{ .code = "ss".*, .name = "Swati" },
    .{ .code = "st".*, .name = "Southern Sotho" },
    .{ .code = "su".*, .name = "Sundanese" },
    .{ .code = "sv".*, .name = "Swedish" },
    .{ .code = "sw".*, .name = "Swahili (macrolanguage)" },
    .{ .code = "ta".*, .name = "Tamil" },
    .{ .code = "te".*, .name = "Telugu" },
    .{ .code = "tg".*, .name = "Tajik" },
    .{ .code = "th".*, .name = "Thai" },
    .{ .code = "ti".*, .name = "Tigrinya" },
    .{ .code = "tk".*, .name = "Turkmen" },
    .{ .code = "tl".*, .name = "Tagalog" },
    .{ .code = "tn".*, .name = "Tswana" },
    .{ .code = "to".*, .name = "Tonga (Tonga Islands)" },
    .{ .code = "tr".*, .name = "Turkish" },
    .{ .code = "ts".*, .name = "Tsonga" },
    .{ .code = "tt".*, .name = "Tatar" },
    .{ .code = "tw".*, .name = "Twi" },
    .{ .code = "ty".*, .name = "Tahitian" },
    .{ .code = "ug".*, .name = "Uighur" },
    .{ .code = "uk".*, .name = "Ukrainian" },
    .{ .code = "ur".*, .name = "Urdu" },
    .{ .code = "uz".*, .name = "Uzbek" },
    .{ .code = "ve".*, .name = "Venda" },
    .{ .code = "vi".*, .name = "Vietnamese" },
    .{ .code = "vo".*, .name = "Volapük" },
    .{ .code = "wa".*, .name = "Walloon" },
    .{ .code = "wo".*, .name = "Wolof" },
    .{ .code = "xh".*, .name = "Xhosa" },
    .{ .code = "yi".*, .name = "Yiddish" },
    .{ .code = "yo".*, .name = "Yoruba" },
    .{ .code = "za".*, .name = "Zhuang" },
    .{ .code = "zh".*, .name = "Chinese" },
    .{ .code = "zu".*, .name = "Zulu" },
};

/// ISO 15924 script codes, sorted.
pub const scripts = [_]Script{
    .{ .code = "Adlm".*, .name = "Adlam" },
    .{ .code = "Afak".*, .name = "Afaka" },
    .{ .code = "Aghb".*, .name = "Caucasian Albanian" },
    .{ .code = "Ahom".*, .name = "Ahom, Tai Ahom" },
    .{ .code = "Arab".*, .name = "Arabic" },
    .{ .code = "Aran".*, .name = "Arabic (Nastaliq variant)" },
    .{ .code = "Armi".*, .name = "Imperial Aramaic" },
    .{ .code = "Armn".*, .name = "Armenian" },
    .{ .code = "Avst".*, .name = "Avestan" },
    .{ .code = "Bali".*, .name = "Balinese" },
    .{ .code = "Bamu".*, .name = "Bamum" },
    .{ .code = "Bass".*, .name = "Bassa Vah" },
    .{ .code = "Batk".*, .name = "Batak" },
    .{ .code = "Beng".*, .name = "Bengali (Bangla)" },
    .{ .code = "Berf".*, .name = "Beria Erfe" },
    .{ .code = "Bhks".*, .name = "Bhaiksuki" },
    .{ .code = "Blis".*, .name = "Blissymbols" },
    .{ .code = "Bopo".*, .name = "Bopomofo" },
    .{ .code = "Brah".*, .name = "Brahmi" },
    .{ .code = "Brai".*, .name = "Braille" },
    .{ .code = "Bugi".*, .name = "Buginese" },
    .{ .code = "Buhd".*, .name = "Buhid" },
    .{ .code = "Cakm".*, .name = "Chakma" },
    .{ .code = "Cans".*, .name = "Unified Canadian Aboriginal Syllabics" },
    .{ .code = "Cari".*, .name = "Carian" },
    .{ .code = "Cham".*, .name = "Cham" },
    .{ .code = "Cher".*, .name = "Cherokee" },
    .{ .code = "Chis".*, .name = "Chisoi" },
    .{ .code = "Chrs".*, .name = "Chorasmian" },
    .{ .code = "Cirt".*, .name = "Cirth" },
    .{ .code = "Copt".*, .name = "Coptic" },
    .{ .code = "Cpmn".*, .name = "Cypro-Minoan" },
    .{ .code = "Cprt".*, .name = "Cypriot syllabary" },
    .{ .code = "Cyrl".*, .name = "Cyrillic" },
    .{ .code = "Cyrs".*, .name = "Cyrillic (Old Church Slavonic variant)" },
    .{ .code = "Deva".*, .name = "Devanagari (Nagari)" },
    .{ .code = "Diak".*, .name = "Dives Akuru" },
    .{ .code = "Dogr".*, .name = "Dogra" },
    .{ .code = "Dsrt".*, .name = "Deseret (Mormon)" },
    .{ .code = "Dupl".*, .name = "Duployan shorthand, Duployan stenography" },
    .{ .code = "Egyd".*, .name = "Egyptian demotic" },
    .{ .code = "Egyh".*, .name = "Egyptian hieratic" },
    .{ .code = "Egyp".*, .name = "Egyptian hieroglyphs" },
    .{ .code = "Elba".*, .name = "Elbasan" },
    .{ .code = "Elym".*, .name = "Elymaic" },
    .{ .code = "Ethi".*, .name = "Ethiopic (Geʻez)" },
    .{ .code = "Gara".*, .name = "Garay" },
    .{ .code = "Geok".*, .name = "Khutsuri (Asomtavruli and Nuskhuri)" },
    .{ .code = "Geor".*, .name = "Georgian (Mkhedruli and Mtavruli)" },
    .{ .code = "Glag".*, .name = "Glagolitic" },
    .{ .code = "Gong".*, .name = "Gunjala Gondi" },
    .{ .code = "Gonm".*, .name = "Masaram Gondi" },
    .{ .code = "Goth".*, .name = "Gothic" },
    .{ .code = "Gran".*, .name = "Grantha" },
    .{ .code = "Grek".*, .name = "Greek" },
    .{ .code = "Gujr".*, .name = "Gujarati" },
    .{ .code = "Gukh".*, .name = "Gurung Khema" },
    .{ .code = "Guru".*, .name = "Gurmukhi" },
    .{ .code = "Hanb".*, .name = "Han with Bopomofo (alias for Han + Bopomofo)" },
    .{ .code = "Hang".*, .name = "Hangul (Hangŭl, Hangeul)" },
    .{ .code = "Hani".*, .name = "Han (Hanzi, Kanji, Hanja)" },
    .{ .code = "Hano".*, .name = "Hanunoo (Hanunóo)" },
    .{ .code = "Hans".*, .name = "Han (Simplified variant)" },
    .{ .code = "Hant".*, .name = "Han (Traditional variant)" },
    .{ .code = "Hatr".*, .name = "Hatran" },
    .{ .code = "Hebr".*, .name = "Hebrew" },
    .{ .code = "Hira".*, .name = "Hiragana" },
    .{ .code = "Hluw".*, .name = "Anatolian Hieroglyphs (Luwian Hieroglyphs, Hittite Hieroglyphs)" },
    .{ .code = "Hmng".*, .name = "Pahawh Hmong" },
    .{ .code = "Hmnp".*, .name = "Nyiakeng Puachue Hmong" },
    .{ .code = "Hntl".*, .name = "Han (Traditional variant) with Latin (alias for Hant + Latn)" },
    .{ .code = "Hrkt".*, .name = "Japanese syllabaries (alias for Hiragana + Katakana)" },
    .{ .code = "Hung".*, .name = "Old Hungarian (Hungarian Runic)" },
    .{ .code = "Inds".*, .name = "Indus (Harappan)" },
    .{ .code = "Ital".*, .name = "Old Italic (Etruscan, Oscan, etc.)" },
    .{ .code = "Jamo".*, .name = "Jamo (alias for Jamo subset of Hangul)" },
    .{ .code = "Java".*, .name = "Javanese" },
    .{ .code = "Jpan".*, .name = "Japanese (alias for Han + Hiragana + Katakana)" },
    .{ .code = "Jurc".*, .name = "Jurchen" },
    .{ .code = "Kali".*, .name = "Kayah Li" },
    .{ .code = "Kana".*, .name = "Katakana" },
    .{ .code = "Kawi".*, .name = "Kawi" },
    .{ .code = "Khar".*, .name = "Kharoshthi" },
    .{ .code = "Khmr".*, .name = "Khmer" },
    .{ .code = "Khoj".*, .name = "Khojki" },
    .{ .code = "Kitl".*, .name = "Khitan large script" },
    .{ .code = "Kits".*, .name = "Khitan small script" },
    .{ .code = "Knda".*, .name = "Kannada" },
    .{ .code = "Kore".*, .name = "Korean (alias for Hangul + Han)" },
    .{ .code = "Kpel".*, .name = "Kpelle" },
    .{ .code = "Krai".*, .name = "Kirat Rai" },
    .{ .code = "Kthi".*, .name = "Kaithi" },
    .{ .code = "Lana".*, .name = "Tai Tham (Lanna)" },
    .{ .code = "Laoo".*, .name = "Lao" },
    .{ .code = "Latf".*, .name = "Latin (Fraktur variant)" },
    .{ .code = "Latg".*, .name = "Latin (Gaelic variant)" },
    .{ .code = "Latn".*, .name = "Latin" },
    .{ .code = "Leke".*, .name = "Leke" },
    .{ .code = "Lepc".*, .name = "Lepcha (Róng)" },
    .{ .code = "Limb".*, .name = "Limbu" },
    .{ .code = "Lina".*, .name = "Linear A" },
    .{ .code = "Linb".*, .name = "Linear B" },
    .{ .code = "Lisu".*, .name = "Lisu (Fraser)" },
    .{ .code = "Loma".*, .name = "Loma" },
    .{ .code = "Lyci".*, .name = "Lycian" },
    .{ .code = "Lydi".*, .name = "Lydian" },
    .{ .code = "Mahj".*, .name = "Mahajani" },
    .{ .code = "Maka".*, .name = "Makasar" },
    .{ .code = "Mand".*, .name = "Mandaic, Mandaean" },
    .{ .code = "Mani".*, .name = "Manichaean" },
    .{ .code = "Marc".*, .name = "Marchen" },
    .{ .code = "Maya".*, .name = "Mayan hieroglyphs" },
    .{ .code = "Medf".*, .name = "Medefaidrin (Oberi Okaime, Oberi Ɔkaimɛ)" },
    .{ .code = "Mend".*, .name = "Mende Kikakui" },
    .{ .code = "Merc".*, .name = "Meroitic Cursive" },
    .{ .code = "Mero".*, .name = "Meroitic Hieroglyphs" },
    .{ .code = "Mlym".*, .name = "Malayalam" },
    .{ .code = "Modi".*, .name = "Modi, Moḍī" },
    .{ .code = "Mong".*, .name = "Mongolian" },
    .{ .code = "Moon".*, .name = "Moon (Moon code, Moon script, Moon type)" },
    .{ .code = "Mroo".*, .name = "Mro, Mru" },
    .{ .code = "Mtei".*, .name = "Meitei Mayek (Meithei, Meetei)" },
    .{ .code = "Mult".*, .name = "Multani" },
    .{ .code = "Mymr".*, .name = "Myanmar (Burmese)" },
    .{ .code = "Nagm".*, .name = "Nag Mundari" },
    .{ .code = "Nand".*, .name = "Nandinagari" },
    .{ .code = "Narb".*, .name = "Old North Arabian (Ancient North Arabian)" },
    .{ .code = "Nbat".*, .name = "Nabataean" },
    .{ .code = "Newa".*, .name = "Newa, Newar, Newari, Nepāla lipi" },
    .{ .code = "Nkdb".*, .name = "Naxi Dongba (na²¹ɕi³³ to³³ba²¹, Nakhi Tomba)" },
    .{ .code = "Nkgb".*, .name = "Naxi Geba (na²¹ɕi³³ gʌ²¹ba²¹, 'Na-'Khi ²Ggŏ-¹baw, Nakhi Geba)" },
    .{ .code = "Nkoo".*, .name = "N’Ko" },
    .{ .code = "Nshu".*, .name = "Nüshu" },
    .{ .code = "Ogam".*, .name = "Ogham" },
    .{ .code = "Olck".*, .name = "Ol Chiki (Ol Cemet’, Ol, Santali)" },
    .{ .code = "Onao".*, .name = "Ol Onal" },
    .{ .code = "Orkh".*, .name = "Old Turkic, Orkhon Runic" },
    .{ .code = "Orya".*, .name = "Oriya (Odia)" },
    .{ .code = "Osge".*, .name = "Osage" },
    .{ .code = "Osma".*, .name = "Osmanya" },
    .{ .code = "Ougr".*, .name = "Old Uyghur" },
    .{ .code = "Palm".*, .name = "Palmyrene" },
    .{ .code = "Pauc".*, .name = "Pau Cin Hau" },
    .{ .code = "Pcun".*, .name = "Proto-Cuneiform" },
    .{ .code = "Pelm".*, .name = "Proto-Elamite" },
    .{ .code = "Perm".*, .name = "Old Permic" },
    .{ .code = "Phag".*, .name = "Phags-pa" },
    .{ .code = "Phli".*, .name = "Inscriptional Pahlavi" },
    .{ .code = "Phlp".*, .name = "Psalter Pahlavi" },
    .{ .code = "Phlv".*, .name = "Book Pahlavi" },
    .{ .code = "Phnx".*, .name = "Phoenician" },
    .{ .code = "Piqd".*, .name = "Klingon (KLI pIqaD)" },
    .{ .code = "Plrd".*, .name = "Miao (Pollard)" },
    .{ .code = "Prti".*, .name = "Inscriptional Parthian" },
    .{ .code = "Psin".*, .name = "Proto-Sinaitic" },
    .{ .code = "Qaaa".*, .name = "Reserved for private use (start)" },
    .{ .code = "Qabx".*, .name = "Reserved for private use (end)" },
    .{ .code = "Ranj".*, .name = "Ranjana" },
    .{ .code = "Rjng".*, .name = "Rejang (Redjang, Kaganga)" },
    .{ .code = "Rohg".*, .name = "Hanifi Rohingya" },
    .{ .code = "Roro".*, .name = "Rongorongo" },
    .{ .code = "Runr".*, .name = "Runic" },
    .{ .code = "Samr".*, .name = "Samaritan" },
    .{ .code = "Sara".*, .name = "Sarati" },
    .{ .code = "Sarb".*, .name = "Old South Arabian" },
    .{ .code = "Saur".*, .name = "Saurashtra" },
    .{ .code = "Seal".*, .name = "(Small) Seal" },
    .{ .code = "Sgnw".*, .name = "SignWriting" },
    .{ .code = "Shaw".*, .name = "Shavian (Shaw)" },
    .{ .code = "Shrd".*, .name = "Sharada, Śāradā" },
    .{ .code = "Shui".*, .name = "Shuishu" },
    .{ .code = "Sidd".*, .name = "Siddham, Siddhaṃ, Siddhamātṛkā" },
    .{ .code = "Sidt".*, .name = "Sidetic" },
    .{ .code = "Sind".*, .name = "Khudawadi, Sindhi" },
    .{ .code = "Sinh".*, .name = "Sinhala" },
    .{ .code = "Sogd".*, .name = "Sogdian" },
    .{ .code = "Sogo".*, .name = "Old Sogdian" },
    .{ .code = "Sora".*, .name = "Sora Sompeng" },
    .{ .code = "Soyo".*, .name = "Soyombo" },
    .{ .code = "Sund".*, .name = "Sundanese" },
    .{ .code = "Sunu".*, .name = "Sunuwar" },
    .{ .code = "Sylo".*, .name = "Syloti Nagri" },
    .{ .code = "Syrc".*, .name = "Syriac" },
    .{ .code = "Syre".*, .name = "Syriac (Estrangelo variant)" },
    .{ .code = "Syrj".*, .name = "Syriac (Western variant)" },
    .{ .code = "Syrn".*, .name = "Syriac (Eastern variant)" },
    .{ .code = "Tagb".*, .name = "Tagbanwa" },
    .{ .code = "Takr".*, .name = "Takri, Ṭākrī, Ṭāṅkrī" },
    .{ .code = "Tale".*, .name = "Tai Le" },
    .{ .code = "Talu".*, .name = "New Tai Lue" },
    .{ .code = "Taml".*, .name = "Tamil" },
    .{ .code = "Tang".*, .name = "Tangut" },
    .{ .code = "Tavt".*, .name = "Tai Viet" },
    .{ .code = "Tayo".*, .name = "Tai Yo" },
    .{ .code = "Telu".*, .name = "Telugu" },
    .{ .code = "Teng".*, .name = "Tengwar" },
    .{ .code = "Tfng".*, .name = "Tifinagh (Berber)" },
    .{ .code = "Tglg".*, .name = "Tagalog (Baybayin, Alibata)" },
    .{ .code = "Thaa".*, .name = "Thaana" },
    .{ .code = "Thai".*, .name = "Thai" },
    .{ .code = "Tibt".*, .name = "Tibetan" },
    .{ .code = "Tirh".*, .name = "Tirhuta" },
    .{ .code = "Tnsa".*, .name = "Tangsa" },
    .{ .code = "Todr".*, .name = "Todhri" },
    .{ .code = "Tols".*, .name = "Tolong Siki" },
    .{ .code = "Toto".*, .name = "Toto" },
    .{ .code = "Tutg".*, .name = "Tulu-Tigalari" },
    .{ .code = "Ugar".*, .name = "Ugaritic" },
    .{ .code = "Vaii".*, .name = "Vai" },
    .{ .code = "Visp".*, .name = "Visible Speech" },
    .{ .code = "Vith".*, .name = "Vithkuqi" },
    .{ .code = "Wara".*, .name = "Warang Citi (Varang Kshiti)" },
    .{ .code = "Wcho".*, .name = "Wancho" },
    .{ .code = "Wole".*, .name = "Woleai" },
    .{ .code = "Xpeo".*, .name = "Old Persian" },
    .{ .code = "Xsux".*, .name = "Cuneiform, Sumero-Akkadian" },
    .{ .code = "Yezi".*, .name = "Yezidi" },
    .{ .code = "Yiii".*, .name = "Yi" },
    .{ .code = "Zanb".*, .name = "Zanabazar Square (Zanabazarin Dörböljin Useg, Xewtee Dörböljin Bicig, Horizontal Square Script)" },
    .{ .code = "Zinh".*, .name = "Code for inherited script" },
    .{ .code = "Zmth".*, .name = "Mathematical notation" },
    .{ .code = "Zsye".*, .name = "Symbols (Emoji variant)" },
    .{ .code = "Zsym".*, .name = "Symbols" },
    .{ .code = "Zxxx".*, .name = "Code for unwritten documents" },
    .{ .code = "Zyyy".*, .name = "Code for undetermined script" },
    .{ .code = "Zzzz".*, .name = "Code for uncoded script" },
};
